---
- name: Setup the docker-storage for overlay
  template:
    src: docker_storage_setup.j2
    dest: /etc/sysconfig/docker-storage-setup
    owner: root
    group: root
    mode: 0664
  when:
    - docker_storage_setup_options.storage_driver is defined
